apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: share-renderer
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
    - host: share.saegim.clab.one
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: share-renderer
                port:
                  number: 8080
  tls:
    - hosts:
        - share.saegim.clab.one
      secretName: share-renderer-tls
