apiVersion: v1
kind: Service
metadata:
  name: share-renderer
  labels:
    app: share-renderer
spec:
  selector:
    app: share-renderer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
